### ISSUE TITLE
Use analytic specific function tables 

### ISSUE THREAD

**Issue by edward-burn** [oxford-pharmacoepi/omopViewer#105]
Using analytic specific function tables where possible should lead to better looking defaults. 

For example, this is what is shown by default by omopviewer for cohort code use
![image](https://github.com/user-attachments/assets/0dc1018a-fd09-4db8-a270-80808f5b7323)

But this is the analytic specific function default
![image](https://github.com/user-attachments/assets/55657bd6-e875-4104-bfa3-2129e8510170)

**Comment by catalamarti** [comment]
Support added for CohortCharacteristics #151
