### ISSUE TITLE
ability to rename tabs

### ISSUE THREAD

**Issue by edward-burn** [oxford-pharmacoepi/omopViewer#129]
I think it would be nice to allow the user to rename the result tabs. Perhaps this could be supported through the panels argument - if a named list is passed like below then the name would be used for the corresponding tab

```
  result |>
    omopViewer::exportStaticApp(
      panels = list(
                   "snapshot" = "summarise_omop_snapshot",
                    "lsc" = "summarise_large_scale_characteristics")
    )
```

**Comment by catalamarti** [comment]
#144
