### ISSUE TITLE
Separate &&& into columns

### ISSUE THREAD

**Issue by albertpratsu** [oxford-pharmacoepi/omopViewer#23]
In tables with additional levels, would be good if &&& separators can be turn into columns and can be filtered

**Comment by catalamarti** [comment]
Thats what tidy/splitStrata/splitGroup/splitAdditional do. Thats why I was Saying always to display in raw, tidy, table and plot tabs.
@albertpratsu

**Comment by catalamarti** [comment]
https://github.com/oxford-pharmacoepi/omopViewer/issues/8
we can consider not do display raw and only use the tidy format which probably it is easier to interpret and analyse but different for each tab

**Comment by MimiYuchenGuo** [comment]
Thanks for the input, @catalamarti

However, there are some challenges as @albertpratsu mentioned filtering by new columns. Users currently filter columns first, then generate plots based on the filtered table. Allowing filtering after splitgroup() disrupts plot functions, with columns like cohort_name_reference and cohort_name_comparator.

To address this, we have three options:

1. Implement a function to revert these columns back to the normal summarized result data (with group_level, group_name, etc.) so the current plot functions work. This function might already exist, but I'm unaware of it.
2. Only display the tidy table, prevent the user from filtering the table after tidy (splitgroup and other split functions). From my understanding, this is not what @albertpratsu is suggesting.
3. Change the plot functionality in CohortCharacteristic.

Which option do you think is best?

**Comment by catalamarti** [comment]
So we can have some methods for filtering
visOmopResults::filterGroup(cohort_name == "acetaminophen")
visOmopResults::filterStrata(sex == "Female") or sth like this @nmercadeb @edward-burn 
But also happy to discuss 1 or 3 @MimiYuchenGuo

**Comment by MimiYuchenGuo** [comment]
https://darwin-eu.github.io/visOmopResults/reference/uniteAdditional.html

https://darwin-eu.github.io/visOmopResults/reference/uniteGroup.html
