### ISSUE TITLE
Binding all csv -> end up with some same result_id 

### ISSUE THREAD

**Issue by MimiYuchenGuo** [oxford-pharmacoepi/omopViewer#27]
When trying with some study results, found one problem with this uploading zip, is that one may update multiple summarised result csvs, and all of them have the same result_id, then just doing rbind will cause problem.

does omopgeneric::bind does not work with local tables? if so it may be easier to bind all summarised result csvs and make sure to get different result ids

**Comment by catalamarti** [comment]
If tou have two summarised result objects and you use bind. It will automatically update the result_id column to be unique
@MimiYuchenGuo
