### ISSUE TITLE
splitBySettings

### ISSUE THREAD

**Issue by edward-burn** [oxford-pharmacoepi/omopViewer#34]
Is this necessary? Is this functionality not already provided by omopgenerics/ visomopresults?

**Comment by catalamarti** [comment]
yep, but I needed it so I built it, but the idea was to move this function somewhere

**Comment by catalamarti** [comment]
do you think it would be useful for visOmopResults @nmercadeb

**Comment by catalamarti** [comment]
https://github.com/darwin-eu/visOmopResults/issues/169
