### ISSUE TITLE
Flexibility around logo

### ISSUE THREAD

**Issue by edward-burn** [oxford-pharmacoepi/omopViewer#38]
It would be nice to make the code more general. For example instead of hardworking the hds logo, it would be nice if there was an argument where a logo could be specified (and the user can then decide what logo to use, or not to use one at all)

https://github.com/oxford-pharmacoepi/omopViewer/blob/e6d8232efae6165df9384ab576bb4e545a1a128a/R/about.R#L27

**Comment by catalamarti** [comment]
- exportShiny can have a logo argument:
  - If `logo` = `NULL` no logo is provided.
  - If `logo` = `HDS` (default) the logo of hds is provided (we can consider adding more default logos in the future).
  - If `logo` = "path/to/image" that image is used as logo
