### ISSUE TITLE
Consider defining some themes with `bslib::bs_theme()`

### ISSUE THREAD

**Issue by catalamarti** [oxford-pharmacoepi/omopViewer#45]
There are some options:

1.  Themes could be exported data:
```
ovTheme <- bslib::bs_theme(bg = "#bb0a1e", fg = "#0000ff")
usethis::use_data(ovTheme)
```
+ documentation of the exported object

2.  Themes could be functions of the package:
```
#' These is a bslib theme defined by `omopViewer`
#'
#' @return A `bs_theme` object.
#' @export
#'
ovTheme <- function() {
  bslib::bs_theme(bg = "#bb0a1e", fg = "#0000ff")
}
```

3.  Themes could be exported from a single function:
```
#' Obtain theme from the theme name.
#'
#' @param themeName Name of the theme.
#'
#' @return A `bs_theme` object.
#' @export
#'
ovTheme <- function(themeName) {
  switch(themeName,
    "theme1" = bslib::bs_theme(bg = "#bb0a1e", fg = "#0000ff")
  )
}
```

**Comment by nmercadeb** [comment]
Something linke the 3rd option is in `visOmopResults` (https://darwin-eu.github.io/visOmopResults/reference/tableStyle.html)
Currently there's only the default theme but we could have themes related to the ones in omopViewer for tables and plots ([visOmopResults #](https://github.com/darwin-eu/visOmopResults/issues/261))

**Comment by catalamarti** [comment]
That would be amazing! And would make sense, we have to investigate the themes and see how we can relate them. Each theme has primary, secondary and other colours associated, we could potentially relate the theme colours with the tables colour. Lats chat about that

**Comment by edward-burn** [comment]
to do - implement 1 first

think about extending in the future
