### ISSUE TITLE
Include ohdsi logo as option

### ISSUE THREAD

**Issue by edward-burn** [oxford-pharmacoepi/omopViewer#58]
https://github.com/OHDSI/VisualIdentity

**Comment by catalamarti** [comment]
This can be easily done copying the logo here:
https://github.com/oxford-pharmacoepi/omopViewer/blob/123b8a561cc4ecc113a0cf2cc41021c4ce8bac51/R/staticShiny.R#L86-L105
and adding the logo as svg in:  https://github.com/oxford-pharmacoepi/omopViewer/tree/123b8a561cc4ecc113a0cf2cc41021c4ce8bac51/inst/images
