### ISSUE TITLE
add at the beginning of global the libraries that are needed

### ISSUE THREAD

**Issue by catalamarti** [oxford-pharmacoepi/omopViewer#76]
library(dplyr)
library(...)

**Comment by cecicampanile** [comment]
After ui and server are written: line https://github.com/oxford-pharmacoepi/omopViewer/blob/96de06717e17e43ca45993b2127e955c42f58d3e/R/appStatic.R#L52
 modify global to include libray() of the packages used im server and/or server. You can identify the packages used searching for the "::".

**Comment by catalamarti** [comment]
to include only libraries used in 'ui' or 'server'
