### ISSUE TITLE
ability to group tabs 

### ISSUE THREAD

**Issue by edward-burn** [oxford-pharmacoepi/omopViewer#87]
It would be nice to have the functionality to create groups of tabs (e.g. so I could have one set of tabs on codelist diagnostics and a second set of tabs on cohort diagnostics (perhaps could be combined with #86 in a single new argument where the user can pass a list)

![image](https://github.com/user-attachments/assets/f13c1385-260f-4fa3-981c-ac4f7ff1e11f)

**Comment by catalamarti** [comment]
copied your comment to #60 so we do not have duplicated issues
